name: Build Next.js web application
on: push
jobs:
    build-project:
        name: Build project
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/Checkout@v3
        - name: Install NPM dependencies
          run: npm install
        - name: Build project assets
          run: npm run build
        - name: Upload static site content
          uses: actions/upload-artifact@v4
          with:
            name: static-site
            path: ./out/
    release-project:
        name: Release project
        runs-on: ubuntu-latest
        needs: build-project
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: static-site
            - name: Test artifact download
              run: ls -R

