name: Test matrix run
on: push
jobs:
    build:
        strategy:
            matrix:
                node: [14, 16]
        runs-on: ubuntu-latest
        steps:
            - name: Node version
              run: node --version

